-- Insert a test restaurant for API testing
INSERT INTO companies (
  name,
  slug,
  description,
  logo_url,
  website,
  phone,
  address,
  city,
  state,
  zip_code,
  country,
  latitude,
  longitude,
  cuisine_type,
  price_range,
  restaurant_hours,
  is_restaurant,
  created_at,
  updated_at
) VALUES (
  'Test Pizza Palace',
  'test-pizza-palace',
  'A test restaurant for API testing with delicious Italian cuisine',
  'https://example.com/pizza-logo.jpg',
  'https://testpizzapalace.com',
  '(555) 123-4567',
  '123 Test Street',
  'Test City',
  'CA',
  '90210',
  'US',
  37.7749,
  -122.4194,
  'Italian',
  '$$',
  '{"monday": "9:00-22:00", "tuesday": "9:00-22:00", "wednesday": "9:00-22:00", "thursday": "9:00-22:00", "friday": "9:00-23:00", "saturday": "9:00-23:00", "sunday": "10:00-21:00"}',
  true,
  NOW(),
  NOW()
) ON CONFLICT (slug) DO NOTHING;
